### ISSUE TITLE
Can we have one header template for all columns header `f-table-schema` 

### ISSUE THREAD

**Issue by VivekY1098** [cldcvr/flow-core#174]
**Is your feature request related to a problem? Please describe.**
currently, we need to provide the same template for all column headers.

**Describe the solution you'd like**
Can we have a common header template if we have the same template for all column headers?

**Describe alternatives you've considered**

**Additional context**
<img width="770" alt="Screenshot 2023-10-18 at 5 08 31 PM" src="https://github.com/cldcvr/flow-core/assets/105432992/4242a1ad-de73-41db-b1e2-fd4794429f17">

**Comment by vikas-cldcvr** [comment]
@VivekY1098 

We have `:header-cell-template.prop` on `f-table-schema`.

<img width="760" alt="Screenshot 2023-10-18 at 5 11 47 PM" src="https://github.com/cldcvr/flow-core/assets/67629551/b5e81379-6135-46a8-a466-f0f0ba195de2">

**Comment by vikas-cldcvr** [comment]
@VivekY1098 
Please refer this story for more context

https://flow.cldcvr.com/v2/index.html?path=/story/cldcvr-flow-table-f-table-schema--header-cell-template

<img width="1496" alt="Screenshot 2023-10-18 at 5 15 21 PM" src="https://github.com/cldcvr/flow-core/assets/67629551/4ee4c8f8-50b5-4fcb-a5b0-54531fe5b635">
